name: CI/CD Hotel Booking

on:
  push:
    branches:
      - main # Kịch bản tự chạy khi bạn push code vào nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ GitHub về máy ảo GitHub Actions
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Java 17 để build project
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Bước 3: Build file .jar bằng Maven (Bỏ qua Unit Test để nhanh hơn)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Bước 4: SSH vào Server và thực hiện các lệnh cập nhật
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 34.101.103.217
          username: minhnhutwork2501
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # 1. Đi vào đúng thư mục bạn vừa tìm thấy
            cd /home/minhnhutwork2501/Hotel-Booking 
            
            # 2. Cập nhật code từ GitHub
            git pull origin main
            
            # 3. Build lại dự án (tạo file .jar mới)
            chmod +x mvnw
            ./mvnw clean package -DskipTests
            
            # 4. Khởi động lại ứng dụng
            # Hãy chắc chắn 'hotel-booking.service' là tên đúng bạn tìm thấy ở bước trước
            sudo systemctl restart hotel-booking.service